# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: savvy-streaming-api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='savvy-streaming-api.proto',
  package='IdekoStreamingDal',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19savvy-streaming-api.proto\x12\x11IdekoStreamingDal\"<\n\x10StreamParameters\x12\x11\n\tmachineId\x18\x01 \x01(\t\x12\x15\n\rauthorization\x18\x02 \x01(\t\"&\n\x0eStreamResponse\x12\x14\n\x0cresponseLine\x18\x01 \x01(\t2p\n\x11SavvyStreamingAPI\x12[\n\rStreamMachine\x12#.IdekoStreamingDal.StreamParameters\x1a!.IdekoStreamingDal.StreamResponse\"\x00\x30\x01\x62\x06proto3')
)




_STREAMPARAMETERS = _descriptor.Descriptor(
  name='StreamParameters',
  full_name='IdekoStreamingDal.StreamParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='machineId', full_name='IdekoStreamingDal.StreamParameters.machineId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='authorization', full_name='IdekoStreamingDal.StreamParameters.authorization', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=108,
)


_STREAMRESPONSE = _descriptor.Descriptor(
  name='StreamResponse',
  full_name='IdekoStreamingDal.StreamResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseLine', full_name='IdekoStreamingDal.StreamResponse.responseLine', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=148,
)

DESCRIPTOR.message_types_by_name['StreamParameters'] = _STREAMPARAMETERS
DESCRIPTOR.message_types_by_name['StreamResponse'] = _STREAMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StreamParameters = _reflection.GeneratedProtocolMessageType('StreamParameters', (_message.Message,), dict(
  DESCRIPTOR = _STREAMPARAMETERS,
  __module__ = 'savvy_streaming_api_pb2'
  # @@protoc_insertion_point(class_scope:IdekoStreamingDal.StreamParameters)
  ))
_sym_db.RegisterMessage(StreamParameters)

StreamResponse = _reflection.GeneratedProtocolMessageType('StreamResponse', (_message.Message,), dict(
  DESCRIPTOR = _STREAMRESPONSE,
  __module__ = 'savvy_streaming_api_pb2'
  # @@protoc_insertion_point(class_scope:IdekoStreamingDal.StreamResponse)
  ))
_sym_db.RegisterMessage(StreamResponse)



_SAVVYSTREAMINGAPI = _descriptor.ServiceDescriptor(
  name='SavvyStreamingAPI',
  full_name='IdekoStreamingDal.SavvyStreamingAPI',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=150,
  serialized_end=262,
  methods=[
  _descriptor.MethodDescriptor(
    name='StreamMachine',
    full_name='IdekoStreamingDal.SavvyStreamingAPI.StreamMachine',
    index=0,
    containing_service=None,
    input_type=_STREAMPARAMETERS,
    output_type=_STREAMRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SAVVYSTREAMINGAPI)

DESCRIPTOR.services_by_name['SavvyStreamingAPI'] = _SAVVYSTREAMINGAPI

# @@protoc_insertion_point(module_scope)
