pipeline {
    agent none

    stages {

        stage('Build') {
           agent {
                dockerfile {
                    filename 'IDEKO-DAL-InfluxDB/Dockerfile.build'
		    //args '-v /home/cloudsigma/jencache/.sbt:/root/.sbt -v /home/cloudsigma/jencache/.ivy2:/root/.ivy2'
                 }
           }
            steps {
                echo "Compiling..."
                //First, create the protobuf"
                sh "cd IDEKO-DAL-InfluxDB-grpc && sbt clean assembly"
                //copy the jar
                sh "mkdir IDEKO-DAL-InfluxDB/lib/"
                sh "cp IDEKO-DAL-InfluxDB-grpc/target/scala-2.12/ideko-dal-influxdb-grpc-assembly-0.1.jar IDEKO-DAL-InfluxDB/lib/"

                //Create the scala-influxdb-client jar file"
                sh "cd scala-influxdb-client && sbt -Dsbt.global.base=.sbt -Dsbt.boot.directory=.sbt -Dsbt.ivy.home=.ivy2 compile && sbt -Dsbt.global.base=.sbt -Dsbt.boot.directory=.sbt -Dsbt.ivy.home=.ivy2 package"
                sh "cp scala-influxdb-client/target/scala-2.12/scala-influxdb-client_2.12-0.6.2-MA.jar IDEKO-DAL-InfluxDB/lib/"
                
                //sh "sbt -Dsbt.global.base=/root/.sbt -Dsbt.boot.directory=/root/.sbt -Dsbt.ivy.home=/root/.ivy2 assembly"
                sh "cd IDEKO-DAL-InfluxDB && sbt -Dsbt.global.base=.sbt -Dsbt.boot.directory=.sbt -Dsbt.ivy.home=.ivy2 universal:packageZipTarball"
                echo "Done."
		    
                // Lets make the JAR available from the artifacts tab in Jenkins
		    
                echo "Archiving artifacts..."
                archiveArtifacts 'IDEKO-DAL-InfluxDB/target/universal/*.tgz'
                echo "Done."

                // Run the tests (we don't use a different stage for improving the performance, another stage would mean another agent)

		        // sh "cd IDEKO-DAL-InfluxDB && sbt -Dsbt.global.base=.sbt -Dsbt.boot.directory=.sbt -Dsbt.ivy.home=.ivy2 test"
            }

            //post {
            //    always {
            //        // Record the jUnit test
            //        junit 'policy-enforcement-engine-api/target/test-reports/*.xml'
            //    }
           // }
        }


         stage('Image creation') {
            agent any
            options {
                // Already compiled the WAR, so don't checkout againg (checkout also cleans the workspace, removing any generated artifact)
                skipDefaultCheckout true
            } 
            steps {
                echo 'Creating the image...'
                archiveArtifacts 'IDEKO-DAL-InfluxDB/Dockerfile.artifact'
                sh "which docker"
                // This will search for a Dockerfile in the src folder and will build the image to the local repository
                // Using latest tag to override tha newest image in the hub
                sh "docker build -t \"ditas/ideko-dal-influxdb:latest\" -f IDEKO-DAL-InfluxDB/Dockerfile.artifact IDEKO-DAL-InfluxDB"
                echo "Done"
            }
        }
        stage('Push image') {
            agent any
            options {
                // Already compiled the assembly, so don't checkout againg (checkout also cleans the workspace, removing any generated artifact)
                skipDefaultCheckout true
            }
            steps {
                echo 'Retrieving Docker Hub password from /opt/ditas-docker-hub.passwd...'
                // Get the password from a file. This reads the file from the host, not the container. Slaves already have the password in there.
                script {
                    password = readFile '/opt/ditas-docker-hub.passwd'
                }
                echo "Done"
                // Login to DockerHub with the ditas generic Docker Hub user
                echo 'Login to Docker Hub as ditasgeneric...'
                sh "docker login -u ditasgeneric -p ${password}"
                echo "Done"
                echo "Pushing the image ditas/ideko-dal-influxdb:latest..."
                // Push the image to DockerHub
                sh "docker push ditas/ideko-dal-influxdb:latest"
                echo "Done"
            }
        }
	stage('Image deploy') {
	    agent any
            options {
                // skip checking out code again 
                skipDefaultCheckout true
            }
	    steps {
	       // Staging environment: 31.171.247.162
    	       // Private key for ssh: /opt/keypairs/ditas-testbed-keypair.pem
	 	// Call the deployment script
		echo "Deploying..."
		sh 'IDEKO-DAL-InfluxDB/jenkins/deploy/deploy-staging.sh'
		echo "Deploy done!"
	   }
	}
    }
}
